# Generated by Django 5.1.7 on 2025-04-23 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_alter_comments_taskid_alter_comments_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdata',
            name='AssignedID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taskdata',
            name='AssignedTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='Management.users'),
        ),
        migrations.AlterField(
            model_name='taskdata',
            name='TaskID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='Management.taskinformation'),
        ),
    ]
