# Generated by Django 5.1.7 on 2025-04-23 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_alter_taskdata_assignedid_alter_taskdata_assignedto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskinformation',
            name='Assignedby',
        ),
        migrations.AlterField(
            model_name='taskinformation',
            name='TaskID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='taskinformation',
            name='AssignedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned', to='Management.users'),
        ),
    ]
