# Generated by Django 5.1.7 on 2025-04-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_remove_taskinformation_assignedby_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='firstname',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='lastname',
            new_name='LastName',
        ),
        migrations.AddField(
            model_name='users',
            name='Email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='Password',
            field=models.CharField(max_length=255),
        ),
    ]
